source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'sqlite3', '1.3.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'gravatar_image_tag', '0.1.0'

group :development do
   gem 'rspec-rails', '2.6.1'
   gem 'annotated_models'
end

group :test do
	gem 'rspec', '2.6.0'
	gem 'webrat', '0.7.1'
	gem 'factory_girl_rails', '1.0'
end